const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FECTH_ROLE_FAILED: "FECTH_ROLE_FAILED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

  FETCH_DOCTOR_SUCCESS: "FETCH_DOCTOR_SUCCESS",
  FETCH_DOCTOR_FAILED: "FETCH_DOCTOR_FAILED",

  FETCH_DOCTOR_SELECT_SUCCESS: "FETCH_DOCTOR_SELECT_SUCCESS",
  FETCH_DOCTOR_SELECT_FAILED: "FETCH_DOCTOR_SELECT_FAILED",

  CREATE_DOCTOR_INFO_SUCCESS: "CREATE_DOCTOR_INFO_SUCCESS",
  CREATE_DOCTOR_INFO_FAILED: "CREATE_DOCTOR_INFO_FAILED",

  GET_DOCTOR_INFO_SUCCESS: "GET_DOCTOR_INFO_SUCCESS",
  GET_DOCTOR_INFO_FAILED: "GET_DOCTOR_INFO_FAILED",
});

export default actionTypes;
